export const SITE_NAME = "MLSA, KIIT Chapter";
export const SITE_NAME_FULL = "Microsoft Learn Student Ambassador, KIIT Chapter";
export const SITE_URL = "https://mlsakiit.tech";
export const SITE_DESCRIPTION = `${SITE_NAME} is a community of students who are interested in learning about the latest technologies and trends in the field of computer science and technology.`;
export const QUOTE = "We encsage young minds to pursue knowledge and excellence in unique ways.";
export const MEDIUM_BLOG_URL = "https://medium.com/msackiit";
export const LINKEDIN_URL = "https://www.linkedin.com/company/msckiit/mycompany/";
export const GITHUB_URL = "";
export const TWITTER_URL = "https://twitter.com/msckiit";
export const INSTAGRAM_URL = "https://www.instagram.com/mlsakiit/";
export const YOUTUBE_URL = "https://www.youtube.com/c/KIITKAKSHA";

export const HERO_SECTION_EVENTS = [
  {
    bgColor: "#9CE7FF",
    img: "/EventItem1.png",
    ProjectName: "Eye S.py Squid",
    date: "16th APRIL 2023",
    numParticipants: "1368 Participants",
    isButton: false,
    link: "",
  },
  {
    bgColor: "#EDFFB9",
    img: "/EventItem2.png",
    ProjectName: "KALKI AR/VR",
    date: " 11th FEBRUARY 2023",
    numParticipants: "844 Participants",
    isButton: false,
    link: "",
  },
  {
    bgColor: "#9CE7FF",
    img: "/EventItem1.png",
    ProjectName: "KALKI Scavenger Hunt",
    date: "11th FEBRUARY 2023",
    numParticipants: "800 Participants",
    isButton: false,
    link: "",
  },
  {
    bgColor: "#EDFFB9",
    img: "/EventItem2.png",
    ProjectName: "Project Wing 3.0",
    date: "13th NOVEMBER 2022",
    numParticipants: "Online Program",
    isButton: false,
    link: "",
  },
];
export const OUR_PROJECTS1 = [
  {
    img: "/projects/browser.webp",
    ProjectName: "Tango Charlie Browser",
    techStack1: "C#",
    techStack2: "HTML",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/c-sharp.svg",
    techImg2:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/html-5.svg",
    github: "https://github.com/MLSAKIIT/TangoBrowser",
  },

  {
    img: "/projects/debate.webp",
    ProjectName: "DebaterX",
    techStack1: "Jupyter Notebook",
    techStack2: "Python",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/jupyter.svg",
    techImg2:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/python.svg",
    github: "https://github.com/MLSAKIIT/DebaterX",
  },
  {
    img: "/projects/code.webp",
    ProjectName: "Code Portal",
    techStack1: "Javascript",
    techStack2: "CSS",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/javascript.svg",
    techImg2:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/css-3.svg",
    github: "https://github.com/MLSAKIIT/MSC-Codeportal",
  },
  {
    img: "/projects/algo.png",
    ProjectName: "Algorithm VE",
    techStack1: "ReactJS",
    techStack2: "SCSS",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/react.svg",
    techImg2:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/sass.svg",
    github: "https://github.com/MLSAKIIT/Algorithm-VE",
  },
  // {
  //   img: "/projects/project1.png",
  //   ProjectName: "OS",
  //   techStack1: "Flutter",
  //   techStack2: "Firebse",
  //   techImg: "/projects/Flutter.png",
  //   techImg2: "/projects/Firebase.png",
  //   github: "#",
  // },
  {
    img: "/projects/daedarus.png",
    ProjectName: "DaeDarus",
    techStack1: "ReactJS",
    techStack2: "NodeJS",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/react.svg",
    techImg2:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/nodejs-icon.svg",
    github: "https://github.com/MLSAKIIT/DaeDarus-Website",
  },
  {
    img: "/projects/flutter.webp",
    ProjectName: "Flutterverse",
    techStack1: "Dart",
    techStack2: "Java",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/dart.svg",
    techImg2:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/java.svg",
    github: "https://github.com/MLSAKIIT/FlutterVerse",
  },
  {
    img: "/projects/project1.png",
    ProjectName: "BubblePod",
    techStack1: "Flask",
    techStack2: "SQL",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/flask.svg",
    techImg2: "https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg",
    github: "https://github.com/MLSAKIIT/Bubblepod-backend",
  },
  {
    img: "/projects/ddos.jpg",
    ProjectName: "DDOS Project Wing",
    techStack1: "Python",
    techStack2: "Numpy",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/python.svg",
    techImg2: "https://www.vectorlogo.zone/logos/numpy/numpy-icon.svg",
    github: "https://github.com/MLSAKIIT/DDoS-project-wing",
  },
  {
    img: "/projects/fing.jpg",
    ProjectName: "Fing Surfers",
    techStack1: "Dart",
    techStack2: "Java",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/dart.svg",
    techImg2:
      "https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg",
    github: "https://github.com/MLSAKIIT/FingSurfers",
  },
  {
    img: "/projects/resume.webp",
    ProjectName: "Resume Nest",
    techStack1: "Dart",
    techStack2: "NodeJS",
    techImg:
      "https://raw.githubusercontent.com/get-icon/geticon/fc0f660daee147afb4a56c64e12bde6486b73e39/icons/dart.svg",
    techImg2: "https://www.vectorlogo.zone/logos/nodejs/nodejs-icon.svg",
    github: "https://github.com/MLSAKIIT/Resumenest",
  },
  {
    img: "/projects/gesturenavigation.png",
    ProjectName: "Gesture Navigation System",
    techStack1: "OpenCV",
    techStack2: "Django",
    techImg: "https://www.vectorlogo.zone/logos/opencv/opencv-icon.svg",
    techImg2: "https://www.vectorlogo.zone/logos/djangoproject/djangoproject-icon.svg",
    github: "https://github.com/MLSAKIIT/Gesture-Navigation-System",
  },
  {
    img: "/projects/face.png",
    ProjectName: "Face Recognition System",
    techStack1: "OpenCV",
    techStack2: "Django",
    techImg: "https://www.vectorlogo.zone/logos/opencv/opencv-icon.svg",
    techImg2: "https://www.vectorlogo.zone/logos/djangoproject/djangoproject-icon.svg",
    github: "",
  },
];
export const OUR_PROJECTS2 = [
  {
    img: "/projects/codeinturn.png",
    ProjectName: "Code In Turn",
    techStack1: "ExpressJS",
    techStack2: "MongoDB",
    techImg: "https://www.vectorlogo.zone/logos/expressjs/expressjs-icon.svg",
    techImg2: "https://www.vectorlogo.zone/logos/mongodb/mongodb-icon.svg",
    github: "https://github.com/MLSAKIIT/Code-In-Turn",
  },
  {
    img: "/projects/music.png",
    ProjectName: "Music Recommendation System",
    techStack1: "Flutter",
    techStack2: "Firebse",
    techImg: "/projects/Flutter.png",
    techImg2: "/projects/Firebase.png",
    github: "https://github.com/MLSAKIIT/Music-Recommendation-Web-App",
  },
  {
    img: "/projects/resume.png",
    ProjectName: "Resumenest",
    techStack1: "Flutter",
    techStack2: "Firebse",
    techImg: "/projects/NextJs.png",
    techImg2: "/projects/Firebase.png",
    github: "https://github.com/MLSAKIIT/Resumenest",
  },
  {
    img: "/projects/project1.png",
    ProjectName: "MSC Task Assigner",
    techStack1: "Flutter",
    techStack2: "Firebse",
    techImg: "/projects/Flutter.png",
    techImg2: "/projects/Firebase.png",
    github: "https://github.com/MLSAKIIT/TaskerMSC",
  },
  {
    img: "/projects/project2.png",
    ProjectName: "Newext",
    techStack1: "MERN",
    techStack2: " ",
    techImg: "/projects/NextJs.png",
    techImg2: "/projects/Firebase.png",
    github: "https://github.com/MLSAKIIT/NEWEXT-1",
  },
  // {
  //   img: "/projects/collab.jpg",
  //   ProjectName: "Collab.mp3",
  //   techStack1: "MERN",
  //   techStack2: "ML, Python",
  //   techImg: "/projects/Python.png",
  //   techImg2: "/projects/Firebase.png",
  //   github: "#",
  // },
  // {
  //   img: "/projects/arcase.jpg",
  //   ProjectName: "AR Case",
  //   techStack1: "TechXR Headset",
  //   techStack2: "Unity, Blender, C#",
  //   techImg: "/projects/Flutter.png",
  //   techImg2: "/projects/Firebase.png",
  //   github: "#",
  // },
  // {
  //   img: "/projects/cicidation.jpg",
  //   ProjectName: "Cicidation",
  //   techStack1: "Python, Selenium",
  //   techStack2: "AWS",
  //   techImg: "/projects/Python.png",
  //   techImg2: "/projects/Firebase.png",
  //   github: "#",
  // },
  {
    img: "/projects/fing.jpg",
    ProjectName: "Fing Surfers",
    techStack1: "ML took kit",
    techStack2: "Flutter , Dart, Flutter games",
    techImg: "/projects/Python.png",
    techImg2: "/projects/Flutter.png",
    github: "https://github.com/MLSAKIIT/FingSurfers",
  },
];

export const ABOUT_US = {
  title: "ABOUT US",
  heading: "We have been doing projects and events since 2017.",
  description:
    "MLSA envisions a world where everyone has access to the benefits of technology. We believe that technology has the potential to be an effective tool for education.We are committed to educating everyone about various tech stacks, thus keeping them updated.",
  our_vision:
    "Our vision is to elevate the coding culture of Kalinga Institute of Industrial Technology, Bhubaneswar by providing opportunities to students to work on projects and boost their analytical and logical skills along with the coding.",
  our_goal:
    "Connecting people with technology and assisting them in using it to enhance their lives are the two main objectives of MLSA. In order to achieve this, we organize events, work on projects, and educate everyone on various tech stacks.",
  our_mission:
    "The mission of MLSA is Tech for All .We empower individuals to embrace the digital world with confidence through engaging events, innovative projects, and meaningful connections. We are dedicated to bridging the technological divides, ensuring that no one is left behind.",
};

export const CONTACT_US = {
  title: "Contact Us",
  heading: "We are always open to new ideas and suggestions.",
  description:
    "If you have any queries or suggestions, feel free to contact us. We will get back to you as soon as possible.",
  email: "hey@mlsakiit.tech",
  phone: {
    primary: "+91 ",
    secondary: "+91 ",
  },
  address: "KIIT University, Bhubaneswar, Odisha, India",
};

export const OUR_DOMAINS = [
  {
    name: "Technical",
    about:
      "Our tech-savvy team of innovators and problem solvers. With their expertise in cutting-edge tools and technologies, they create seamless digital experiences, thus making learning lively and fun",
    imgSrc: "/domainLogos/ComputerSupport.png",
  },
  {
    name: "Creative",
    about:
      "Our team of imaginative minds who breathe life into ideas with their boundless creativity. With their diverse skill sets, they transform visions into stunning works of art, leaving audiences awestruck      ",
    imgSrc: "/domainLogos/PaintBrush.png",
  },
  {
    name: "Operations",
    about:
      "Our operations team is the backbone of our society. With their exceptional organizational skills, they handle logistics, coordination, and resource management, enabling seamless execution of projects and initiatives.",
    imgSrc: "/domainLogos/Idea.png",
  },
  {
    name: "Marketing",
    about:
      "Our team of zealous minds who amplify the voice of MLSA, helping us link with the audience and corporate world. Their creative thinking, market insights, and innovative tactics drive our success.",
    imgSrc: "/domainLogos/Omnichannel.png",
  },
  {
    name: "Youtube",
    about:
      "A team of creative minds who bring our ideas to life. Through their mastery of video storytelling, exceptional editing skills, and a deep understanding of YouTube, they craft engaging content to captivate viewers",
    imgSrc: "/domainLogos/TVShow.png",
  },
  {
    name: "Design",
    about:
      "A team of visionary artists breathing life into ideas through their exceptional skill set. With their keen eye for aesthetics and creative expertise, they transform concepts into stunning visual experiences.",
    imgSrc: "/domainLogos/Vector.png",
  },
];

export const FOUNDER = {
  name: "Achyuta Samanta",
  site: "https://achyutasamanta.com/",
};

export const OUR_ALUMNI = [
  {
    image: "/Alumni/pranav.jpg",
    name: "Parnav Shekar",
    position: "USI Consultant",
    company: "Deloitte",
    message:
      "MSC community helped me embrace self-discovery and learn the significance of humility over power and intelligence, leading to personal growth and fearlessness.",
  },
  {
    image: "/Alumni/ayush.jpeg",
    name: "Ayush Padia",
    position: "Associate Software Engg-1",
    company: "Highradius Technologies",
    message:
      "MSC journey: growth, learning, and joy. Founding team, leading talented KIIT society. Wrong project impact on career, global student positive impact aspirations.",
  },
  {
    image: "/Alumni/Rajatav.jpeg",
    name: "Rajatav Dutta",
    position: "Associate Developer",
    company: "SAP Labs India",
    message:
      " MSC has greatly influenced my personal growth, connecting me with bright minds and fostering my passion. Excited for the community's future achievements and new heights. ",
  },
  {
    image: "/Alumni/ANSHIKA.jpeg",
    name: "Anshika Verma",
    position: "Software Developer",
    company: "IBN ISL Role",
    message:
      " MSC gave me a career and cherished memories, breaking free from corporate cocoons. The unforgettable bond with Pranav, Simran, and Anshika brought life to college, making goodbye difficult.",
  },
  {
    image: "/Alumni/ANKITA.jpeg",
    name: "Ankita Bera",
    position: "Software Developer",
    company: "Optum United Health Group",
    message:
      "You come as a rookie, but you leave like a bawse!, my journey with MSC has been nothing short of incredible with a pinch of awesome.",
  },
  {
    image: "/Alumni/ABHINAV.jpg",
    name: "Abhinav Srivastav",
    position: "SDE-1",
    company: "Highradius Technologies",
    message:
      "Imagining my college life without MSC is hard. We both grew together. It feels more like a family than a community.",
  },
  {
    image: "/Alumni/Taneesh.jpg",
    name: "M Taneesh",
    position: "Associate Software Engineer - I",
    company: "Highradius Technologies",
    message:
      "Had fun building the society during this online era made a few long lasting friendships and experiences :)",
  },
  // {
  //   image: "/Alumni/SIMRAN.jpg",
  //   name: "Simran Banerjee",
  //   position: "USI Consultant",
  //   company: "Deloitte",
  //   message:
  //     "I am so grateful that I got to be a part of this society and work with such amazing people. I made some great friends and learnt so much from each and everyone of them. ",
  // },
];
export const OUR_LEADS = [
  {
    image: "/BgColored_Leads/anvit_bg.jpg",
    name: "Anvit Dubey",
    domain: "Lead",
    message: "lending my hands in developing a better technical society",
    facebook: "",
    linkedIn: "https://www.linkedin.com/in/anvit-dubey-b0a205200",
    instagram: "",
  },
  {
    image: "/BgColored_Leads/saniya_bg.png",
    name: "Saniya Bhargav",
    domain: "Vice Lead",
    message: "lending my hands in developing a better technical society",
    facebook: "",
    linkedIn: "https://www.linkedin.com/in/saniya-bhargav-a660111bb",
    instagram: "",
  },
  {
    image: "/BgColored_Leads/swastika_bg.png",
    name: "Swasktika Bishnoi",
    domain: "Executive",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/swastika-bishnoi",
    facebook: "",
    instagram: "",
  },
  {
    image: "/BgColored_Leads/prashant.png",
    name: "Prashant Upadhyay",
    domain: "Tech Lead",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/prashant-upadhyay254/",
    facebook: "",
    instagram: "",
  },
  {
    image: "/BgColored_Leads/atig_bg.png",
    name: "Atig Purohit",
    domain: "Tech Lead",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/atig-purohit-a83233183/",
    facebook: "",
    instagram: "",
  },
  {
    image: "/Leads/mayank.png",
    name: "Mayank Jain",
    domain: "Creative Lead",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/mayank-jain-688409208/",
    facebook: "",
    instagram: "",
  },
  {
    image: "/BgColored_Leads/aradhya_bg.png",
    name: "Aradhya Kumar",
    domain: "Content Lead",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/aradhya-kumar-84078a21b/",
    facebook: "",
    instagram: "",
  },
  {
    image: "/BgColored_Leads/sagar_bg.png",
    name: "Sagar Satapathy",
    domain: "Treasurer",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/sagar-satapathy-a4579b173/",
    facebook: "",
    instagram: "",
  },
  {
    image: "/BgColored_Leads/ayush_bg.png",
    name: "Ayush Raj",
    domain: "Marketing Lead",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/ayush-raj-9a2585201/",
    facebook: "",
    instagram: "",
  },
  {
    image: "/BgColored_Leads/akshita.png",
    name: "Akshita Sah",
    domain: "Tech Lead",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/akshita-sah/",
    facebook: "",
    instagram: "",
  },

  {
    image: "/BgColored_Leads/rishab_bg.png",
    name: "Rishab Barik",
    domain: "PR/CR Lead",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/rishabbarik/",
    facebook: "",
    instagram: "",
  },
  {
    // image: "/BgColored_Leads/abhinav.png",
    image: "/BgColored_Leads/abhinav.jpg",
    name: "Abhinav Prasad",
    domain: "Web Lead",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/abhinav-prasad-697a67205/",
    facebook: "",
    instagram: "",
  },
  {
    image: "/BgColored_Leads/eshan.png",
    name: "Eshaan Anand",
    domain: "App Lead",
    message: "lending my hands in developing a better technical society",
    linkedIn: "https://www.linkedin.com/in/eshaan-anand2911/",
    facebook: "",
    instagram: "",
  },
];

export const OUR_SPONSORS = [
  {
    name: "PrepBytes",
    site: "https://www.prepbytes.com/",
    image: "/sponsors/prepbytes.png",
    w: 130,
    h: 130,
  },
  {
    name: "RedBull",
    site: "https://www.redbull.com/in-en/",
    image: "/sponsors/redBull.png",

    w: 140,
    h: 88,
  },
  {
    name: "Snapchat",
    site: "https://www.snapchat.com/en-GB",
    image: "/sponsors/snapchat.png",
    w: 140,
    h: 88,
  },
  {
    name: "JetBrains",
    site: "https://www.jetbrains.com/",
    image: "/sponsors/jetBrains.png",
    w: 130,
    h: 130,
  },
  {
    name: "zuno",
    site: "https://www.foundit.in/zuno/",
    image: "/sponsors/zuno.png",
    w: 149,
    h: 41,
  },
  {
    name: "Coding Ninjas",
    site: "https://www.codingninjas.com/",
    image: "/sponsors/codingNinja.png",
    w: 146,
    h: 55,
  },
  {
    name: "SawoLabs",
    site: "https://sawolabs.com/",
    image: "/sponsors/sawolabs.png",
    w: 146,
    h: 500,
  },
  {
    name: "Devfolio",
    site: "https://devfolio.co/",
    image: "/sponsors/devfolio.png",
    w: 146,
    h: 500,
  },
  {
    name: "GeeksforGeeks",
    site: "https://www.geeksforgeeks.org/",
    image: "/sponsors/gfk.png",
    w: 146,
    h: 500,
  },
];

export const EVENTS2023 = [
  // {
  //   bgColor: "#9CE7FF",
  //   img: "/eventImages/eyeSpySquid.jpg",
  //   ProjectName: "Eye S.py Squid",
  //   date: "16th APRIL 2023",
  //   numParticipants: "1368 Participants",
  //   isButton: false,
  //   isHero: false,
  //   link: "",
  //   description:
  //     "A unique event which included designing your own squid game using computer vision.",
  // },
  {
    bgColor: "#9CFFE1",
    img: "/eventImages/kalkiComp.png",
    ProjectName: "KALKI Computer Vision",
    date: "11th February 2023",
    numParticipants: "844 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "Event with an array of captivating experiences based on Computer vision which included Fruit Ninja and Squid games.",
  },
  {
    bgColor: "#FFCC9C",
    img: "/eventImages/kalkiAR.png",
    ProjectName: "KALKI AR/VR",
    date: " 11th February 2023",
    numParticipants: "844 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "KALKI provided amazing experiences ranging from VR games with robotic or non-controller gameplay to movies and 2D games.",
  },
  {
    bgColor: "#7395AE",
    img: "/eventImages/kalkiScav.png",
    ProjectName: "KALKI Scavenger Hunt",
    date: " 11th February 2023",
    numParticipants: "844 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "The most popular scavenger hunt with twisted techy questions that left our audience both overly excited and baffled.",
  },
];

export const EVENTS2022 = [
  {
    bgColor: "#DBAEFF",
    img: "/eventImages/projectWing3.png",
    ProjectName: "Project Wing 3.0",
    date: "13th November 2022",
    numParticipants: "Online Program",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "An online fast-track program aimed at equipping engineering students with standout skills.",
  },
  {
    bgColor: "#9CE1FF",
    img: "/eventImages/hacktoberFest2022.png",
    ProjectName: "HacktoberFest 2022",
    date: "15th - 16th October 2020",
    numParticipants: "533 Participants",
    isButton: false,
    link: "",
    description:
      "A beginner-friendly workshop to spread awareness about Open-Source and HacktoberFest.",
  },
  {
    bgColor: "#D9FF9C",
    img: "/eventImages/devops.jpg",
    ProjectName: "DevOps Workshop",
    date: "3rd September 2022",
    numParticipants: "1302 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "A one-day DevOps Workshop aimed at raising awareness about the concept of operating DevOps.",
  },
  {
    bgColor: "#E3AFBC",
    img: "/eventImages/databyte.jpg",
    ProjectName: "DataByte",
    date: "7th - 8th May, 2022",
    numParticipants: "1302 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "It was a captivating machine learning and data visualisation workshop which used the unique concept of no code tech.",
  },
  {
    bgColor: "#EE4C7C",
    img: "/eventImages/frontendWithBenefits.jpg",
    ProjectName: "FrontEnd with Benefits",
    date: "27th - 28th March, 2021",
    numParticipants: "516 Participants",
    isButton: false,
    link: "",
    description: "It was a two-day hackathon focused on frontend design.",
  },
  {
    bgColor: "#EDC7B7",
    img: "/eventImages/flutterVerse.png",
    ProjectName: "FlutterVerse",
    date: "1st FEBRUARY - 28th February 2022",
    numParticipants: "283 Participants",
    isButton: false,
    link: "",
    description:
      "An all-in-one Workshop on Flutter starting from basics to creating both a minor and a major project.",
  },
];

export const EVENTS2021 = [
  {
    bgColor: "#DBAEFF",
    img: "/eventImages/codeVibe.jpg",
    ProjectName: "Code Vibe",
    date: "21st November, 2021",
    numParticipants: "366 Participants",
    isButton: false,
    link: "",
    description:
      "A competitive programming event with fun packed interactive sessions and no barrier on programming languages.",
  },
  {
    bgColor: "#9CE1FF",
    img: "/eventImages/hacktoberFest2021.jpg",
    ProjectName: "HacktoberFest 2021",
    date: "October, 2021",
    numParticipants: "275 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "This workshop provided an accessible introduction to Open-Source and HacktoberFest.",
  },
  {
    bgColor: "#D9FF9C",
    img: "/eventImages/projectWing2021.jpg",
    ProjectName: "Project Wing 2.0",
    date: "October, 2021",
    numParticipants: "Online event",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "A specialised program intended to empower engineering students by providing them with tech and non-tech skills.",
  },
  {
    bgColor: "#66FCF1",
    img: "/eventImages/daedarusHack.jpg",
    ProjectName: "DeaDarus Hackathon",
    date: "13th - 15th August 2021",
    numParticipants: "837 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "The most awaited hackathon that enables you to construct a labyrinth of ideas, create a project and enable sustainability.",
  },
  {
    bgColor: "#7395AE",
    img: "/eventImages/Mlathon.jpg",
    ProjectName: "MLathon",
    date: "25th June 2021",
    numParticipants: "411 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "A two-day hackathon for every ML lover with loads of quizzes and prediction games and amazing prizes.",
  },
  {
    bgColor: "#379683",
    img: "/eventImages/codeInTurn.jpg",
    ProjectName: "Code-In-Turn",
    date: "2nd - 4th April 2021",
    numParticipants: "603 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "A unique event where participants celebrated their problem-solving skills and got rewarded for it.",
  },
  {
    bgColor: "#B1A296",
    img: "/eventImages/greenHack.jpg",
    ProjectName: "Data Dive",
    date: "6th March 2021",
    numParticipants: "94 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description: "",
  },
];

export const EVENTS2020 = [
  {
    bgColor: "#EDF5E1",
    img: "/eventImages/greenHack.jpg",
    ProjectName: "Green Hack",
    date: "December 2020",
    numParticipants: "200 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description: "",
  },
  {
    bgColor: "#7395AE",
    img: "/eventImages/projectWing2020.jpg",
    ProjectName: "Project Wing 1.0",
    date: "October 2020",
    numParticipants: "Online Event",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "Provided engineering students with a unique program designed to equip them with exceptional skills with projects.",
  },
  {
    bgColor: "#8EE4AF",
    img: "/eventImages/hacktoberFest2020.png",
    ProjectName: "HacktoberFest 2020",
    date: "October 2020",
    numParticipants: "200 Participants",
    isButton: false,
    isHero: false,
    link: "",
    description:
      "With a focus on beginners, this workshop sought to promote Open-Source and HacktoberFest.",
  },
];

// members

export const videoedit = [
  {
    id: 1,
    img: "/members/pratik.JPG",
    name: "Pratik Mohanty",
    domain: "Video Editing",
    github: "http://github.com/pratik123-coder",
    linkedIn: "http://linkedin.com/in/pratikmohantycodes",
    instagram: "http://instagram.com/itspratikmohanty",
  },
  {
    id: 2,
    img: "/members/Shresth Rakesh Kumar.JPG",
    name: "Shresth Rakesh Kumar",
    domain: "Video Editing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 3,
    img: "/members/Parivesh.jpeg",
    name: "Parivesh Srivastava",
    domain: "Video Editing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 4,
    img: "/members/SASWATI PADHY.jpg",
    name: "Saswati Padhy",
    domain: "Video Editing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 5,
    img: "/members/PIYALI MURMU.jpg",
    name: "Piyali Murmu",
    domain: "Video Editing",
    github: "https://github.com/piyacodes",
    linkedIn: "https://www.linkedin.com/in/piyali-murmu/",
    instagram: "https://www.instagram.com/piyaalol/",
  },
  {
    id: 6,
    img: "/members/V N Ayush Mudaliyar.png",
    name: "V N Ayush Mudaliyar",
    domain: "Video Editing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
];

export const Marketing1 = [
  {
    id: 1,
    img: "/members/YASHASWINI SARANGI.jpg",
    name: "Yashaswini Sarangi",
    domain: "Marketing",
    github: "",
    linkedIn: "https://www.linkedin.com/in/yashaswini-sarangi-88b78a251",
    instagram: "https://instagram.com/_.yashaswini..sarangi.?igshid=MjAxZDBhZDhlNA==",
  },
  {
    id: 2,
    img: "/members/2.jpg",
    name: "Debesh Acharya",
    domain: "Marketing",
    github: "",
    linkedIn: "https://www.linkedin.com/in/debesh-acharya-06ba72175",
    instagram: "https://instagram.com/debeshacharya_?igshid=MzNlNGNkZWQ4Mg==",
  },
  {
    id: 3,
    img: "/members/VAISHNAVI SINGH.jpg",
    name: "Vaishnavi Singh",
    domain: "Marketing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 4,
    img: "/members/DHYANAM ATTREYA.jpg",
    name: "Dhyanam Attreya",
    domain: "Marketing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 5,
    img: "/members/Deepika Soni.png",
    name: "Deepika Soni",
    domain: "Marketing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 6,
    img: "/members/RajivMishra.jpg",
    name: "Rajiv Mishra",
    domain: "Marketing",
    github: "",
    linkedIn: "https://www.linkedin.com/in/rajiv-mishra-3389231b3",
    instagram: "",
  },
  {
    id: 7,
    img: "/members/Shouryjeet Gupta.jpeg",
    name: "Shouryjeet Gupta",
    domain: "Marketing",
    github: "",
    linkedIn: "https://www.linkedin.com/in/rajiv-mishra-3389231b3",
    instagram: "",
  },
  {
    id: 8,
    img: "/members/PRANSHU SAHAY.jpg",
    name: "Pranshu Sahay",
    domain: "Marketing",
    github: "https://github.com/Pranshu-Sahay",
    linkedIn: "https://www.linkedin.com/in/pranshu-sahay/",
    instagram: "https://instagram.com/coz.nobody?igshid=NGExMmI2YTkyZg==",
  },
  {
    id: 9,
    img: "/members/GIRISH KYAL.jpg",
    name: "Girish Kayal",
    domain: "Marketing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 10,
    img: "/members/ABHISHREEBHADRA.jpg",
    name: "Abhishree bhadra",
    domain: "Marketing",
    github: "",
    linkedIn: "https://www.linkedin.com/in/abhishree-bhadra-25abb0245/",
    instagram: "https://instagram.com/abhishreebhadra?igshid=MzNlNGNkZWQ4Mg==",
  },
  {
    id: 11,
    img: "/members/ANKIT KUMAR.png",
    name: "Ankit Kumar",
    domain: "Marketing",
    github: "https://github.com/Ankit-kr13",
    linkedIn: "https://www.linkedin.com/in/ankit-kumar-5b1b68205",
    instagram: "https://instagram.com/_ankitkumarr?igshid=MzNlNGNkZWQ4Mg==",
  },
  {
    id: 12,
    img: "/members/Adarsh Kumar Rath.jpg",
    name: "Adarsh Kumar Rath",
    domain: "Marketing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 13,
    img: "/members/Krishna Agrawal.jpg",
    name: "Krishna Agrawal",
    domain: "Marketing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 14,
    img: "/members/UTSAV ANAND.jpg",
    name: "Utsav Anand",
    domain: "Marketing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 15,
    img: "/members/AVINAV ROY.png",
    name: "Avinav Roy",
    domain: "Marketing",
    github: "",
    linkedIn: "https://www.linkedin.com/in/avinav-roy-681a11206/",
    instagram: "https://instagram.com/imaviroy?igshid=ZDdkNTZiNTM=",
  },
  {
    id: 16,
    img: "/members/Anand.jpg",
    name: "Anand",
    domain: "Marketing",
    github: "",
    linkedIn: "",
    instagram: "",
  },
];

export const MachineLearning = [
  {
    id: 1,
    img: "/members/Indranil_Nag.png",
    name: "Indranil Nag",
    domain: "Machine Learning",
    github: "https://github.com/Indranil28",
    linkedIn: "https://www.linkedin.com/in/indranil-nag-658142248/",
    instagram: "https://www.instagram.com/mr._poised/",
  },
  {
    id: 2,
    img: "/members/ATIG PUROHIT.jpeg",
    name: "Atig Purohit",
    domain: "Machine Learning",
    github: "https://github.com/AtigPurohit",
    linkedIn: "https://www.linkedin.com/in/atig-purohit-a83233183",
    instagram: "https://instagram.com/x.___mysterious___.x?igshid=MzNlNGNkZWQ4Mg==",
  },
  {
    id: 3,
    img: "/members/MITUL GOSWAMI.png",
    name: "Mitul Goswami",
    domain: "Machine Learning",
    github: "https://github.com/mitul-goswami",
    linkedIn: "https://www.linkedin.com/in/mitul-goswami-a6114b230/",
    instagram: "https://instagram.com/mitul__95__?igshid=ZDc4ODBmNjlmNQ==",
  },
  {
    id: 4,
    img: "/members/AlokKumarJha.png",
    name: "Alok Kumar Jha",
    domain: "Machine Learning",
    github: "https://github.com/akjalok",
    linkedIn: "https://www.linkedin.com/in/alok-kumar-jha-316572224",
    instagram: "https://instagram.com/alok1877_",
  },
  {
    id: 5,
    img: "/members/ANURAG PRASOON.jpg",
    name: "Anurag Prasoon",
    domain: "Machine Learning",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 6,
    img: "/members/NISHARG.jpg",
    name: "Nisharg Nargund",
    domain: "Machine Learning",
    github: "https://github.com/1nisharg",
    linkedIn: "https://www.linkedin.com/in/nisharg-nargund-6bb385255",
    instagram: "https://instagram.com/nisarg_nargund_official?igshid=ZDc4ODBmNjlmNQ==",
  },
  {
    id: 7,
    img: "/members/ArunopalDutta.png",
    name: "Arunopal Dutta",
    domain: "Machine Learning",
    github: "https://github.com/EpicLulz1509/",
    linkedIn: "https://www.linkedin.com/in/arunopal-dutta-9a1ba1222/",
    instagram: "https://www.instagram.com/arunopal_dutta/",
  },
  {
    id: 8,
    img: "/members/KARTIK AGARWAL.jpeg",
    name: "Kartik Agarwal",
    domain: "Machine Learning",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 9,
    img: "/members/Rohan Volety.jpeg",
    name: "Rohan Volety",
    domain: "Machine Learning",
    github: "https://github.com/RohanVolety",
    linkedIn: "https://www.linkedin.com/in/rohan-volety-30a816221/",
    instagram: "https://instagram.com/rohan_volety?igshid=MzNlNGNkZWQ4Mg==",
  },
  {
    id: 10,
    img: "/members/anir.jpeg",
    name: "Anirban Roy",
    domain: "Machine Learning",
    github: "https://github.com/DeepRoy2002",
    linkedIn: "http://linkedin.com/in/anirban-roy-251360206/",
    instagram: "https://www.instagram.com/anirbandeep2002/",
  },
];

export const GraphicDesign = [
  {
    id: 1,
    img: "/members/ASHISH POTHAL.png",
    name: "Ashish Pothal",
    domain: "Graphic Design",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 2,
    img: "/members/Harsh Singh.jpg",
    name: "Harsh Singh",
    domain: "Graphic Design",
    github: "",
    linkedIn: "",
    instagram: "",
  },
];

export const CreativeTeam = [
  {
    id: 1,
    img: "/members/DAWAR SHAFAQUE.jpg",
    name: "Dawar Shafaque",
    domain: "Creative",
    github: "https://github.com/dawar-shafaque",
    linkedIn: "https://www.linkedin.com/in/dawar-shafaque-219a64229",
    instagram: "https://instagram.com/dawar_shafaque?igshid=NGExMmI2YTkyZg==",
  },
  {
    id: 2,
    img: "/members/sachi.jpg",
    name: "Sachi Verma",
    domain: "Creative",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 3,
    img: "/members/Isha Mishra.jpg",
    name: "Isha Mishra",
    domain: "Creative",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 4,
    img: "/members/TANVI UPADHYAY.jpg",
    name: "Tanvi Upadhyay",
    domain: "Creative",
    github: "https://github.com/Tanvi-upadhyay",
    linkedIn: "https://www.linkedin.com/in/tanvi-upadhyay-b4a985216",
    instagram: "https://www.instagram.com/03_bunny_02/",
  },
  {
    id: 5,
    img: "/members/SAKSHI PATHAK.jpg",
    name: "Sakshi Pathak",
    domain: "Creative",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 6,
    img: "/members/SUDIPTA SUBHAM.jpg",
    name: "Sudipta Subham",
    domain: "Creative",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 7,
    img: "/members/ANUBHAV KAKATI.jpg",
    name: "Anubhav Kakati",
    domain: "Creative",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 8,
    img: "/members/ANKIT MOHAPATRA.jpg",
    name: "Ankit Mohapatra",
    domain: "Creative",
    github: "https://github.com/iamsoankit",
    linkedIn: "https://www.linkedin.com/in/iamsoankitt/",
    instagram: "https://www.instagram.com/iamsoankitt/?hl=en",
  },
  {
    id: 9,
    img: "/members/DIBYOJYOTI DEB.jpg",
    name: "Dibyojyoti Deb",
    domain: "Creative",
    github: "https://github.com/dibyojyoti-deb",
    linkedIn: "https://www.linkedin.com/in/dibyojyoti-deb-38617025b",
    instagram: "https://instagram.com/flaming_phoenix_within?igshid=NGExMmI2YTkyZg==",
  },
];

export const WebDevelopment = [
  {
    id: 1,
    img: "/members/Harshit2.jpg",
    name: "Harshit Yadav",
    domain: "Web Development",
    instagram: "https://www.instagram.com/harshit._._.yadav/",
    github: "https://github.com/CodeMaster17",
    linkedIn: "https://www.linkedin.com/in/harshit-yadav-2b2b2922b/",
  },
  {
    id: 2,
    img: "/members/amaan.jpg",
    name: "Amaan Bhaati",
    domain: "Web Development",
    instagram: "https://www.instagram.com/amaaanbhati/",
    github: "http://github.com/amaan-bhati",
    linkedIn: "https://www.linkedin.com/in/amaan-bhati-6a7105230/",
  },
  {
    id: 3,
    img: "/members/anshul.jpg",
    name: "Anshul Kumar",
    domain: "Web Development",
    instagram: "https://instagram.com/anshul_.kumar?igshid=MzNlNGNkZWQ4Mg==",
    github: "https://github.com/anshulkumarx7",
    linkedIn: "https://www.linkedin.com/in/anshul-kumar-811ab7238/",
  },
  {
    id: 4,
    img: "/members/harsh.jpg",
    name: "Harsh Raj",
    domain: "Web Development",
    instagram: "",
    github: "https://github.com/022003harsh",
    linkedIn: "https://www.linkedin.com/in/harsh-raj-898340217",
  },
  {
    id: 5,
    img: "/members/Untitled.png",
    name: "Akshat Srivastava",
    domain: "Web Development",
    instagram: "https://instagram.com/_blaze_001_?igshid=NGExMmI2YTkyZg==",
    github: "https://github.com/A01Akshat",
    linkedIn: "https://www.linkedin.com/in/akshat-srivastava-23a98b216",
  },
  {
    id: 6,
    img: "/members/MANISH KUMAR.png",
    name: "Manish Kumar",
    domain: "Web Development",
    instagram: "https://www.instagram.com/manishmh/",
    github: "https://www.github.com/manishmh",
    linkedIn: "https://www.linkedin.com/in/manish-k-46101a139/",
  },
  {
    id: 11,
    img: "/members/ANKIT1.jpg",
    name: "Ankit Kumar",
    domain: "Web Development",
    instagram: "https://github.com/sinEscanor",
    github: "https://github.com/sinEscanor",
    linkedIn: "https://www.linkedin.com/in/ankit-kumar-7a9ab3253",
  },
  {
    id: 7,
    img: "/members/GARV AGARWAL.png",
    name: "Garv Agarwal",
    domain: "Web Development",
    instagram: "https://instagram.com/0xgarv?igshid=MzNlNGNkZWQ4Mg==",
    github: "https://github.com/garv-aga",
    linkedIn: "https://www.linkedin.com/in/garv-agarwal-351ab8164",
  },
  {
    id: 8,
    img: "/members/Ashish Mishra.jpeg",
    name: "Ashish Mishra",
    domain: "Web Development",
    instagram: "https://instagram.com/a_s_h__1912?utm_medium=copy_link",
    github: "https://github.com/Ash1912",
    linkedIn: "https://www.linkedin.com/in/ashish-kumar-mishra-616321206",
  },
  {
    id: 9,
    img: "/members/RISHABH KUMAR.jpg",
    name: "Rishabh Kumar",
    domain: "Web Development",
    instagram: "https://www.instagram.com/4rishabh_kumar/?igshid=MzNlNGNkZWQ4Mg%3D%3D",
    github: "https://github.com/Risk-Hub",
    linkedIn: "https://www.linkedin.com/in/rohan-volety-30a816221/",
  },
  {
    id: 10,
    img: "/members/pfp.jpg",
    name: "Yashwardhan Singh",
    domain: "Web Development",
    instagram: "https://instagram.com/_yash.vs_",
    github: "https://github.com/pythonicboat",
    linkedIn: "https://linkedin.com/in/yashvardhan04",
  },
];

export const AndroidDevelopment = [
  {
    id: 1,
    img: "/members/Aritra Pal.jpg",
    name: "Aritra Pal",
    domain: "Android Development",
    github: "https://github.com/AritraPal147",
    linkedIn: "https://www.linkedin.com/in/aritra-pal-755970221",
    instagram: "https://instagram.com/aritrapal147?igshid=ZGUzMzM3NWJiOQ==",
  },
  {
    id: 2,
    img: "/members/Pranshu sarthak.jpg",
    name: "Pranshu Sarthak",
    domain: "Android Development",
    github: "https://github.com/pranshusarthak",
    linkedIn: "https://www.linkedin.com/in/pranshu-sarthak/",
    instagram: "https://www.instagram.com/pranshusarthak/",
  },
  {
    id: 3,
    img: "/members/SHASHANK DEEPAK.jpg",
    name: "Shashank Deepak",
    domain: "Android Development",
    github: "https://github.com/ShashankDeepak",
    linkedIn: "https://www.linkedin.com/in/shashank-deepak-08488922b",
    instagram: "",
  },
  {
    id: 4,
    img: "/members/Shivangi.png",
    name: "Shivangi",
    domain: "Android Development",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 5,
    img: "/members/G Dhvani Iyer.jpeg",
    name: "G Dhvani Iyer",
    domain: "Android Development",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 6,
    img: "/members/shubhankar shahi.jpg",
    name: "Shubhankar Shahi",
    domain: "Android Development",
    github: "https://github.com/Shubhankar5002",
    linkedIn: "https://www.linkedin.com/in/shubhankar-shahi-20b588237",
    instagram: "https://www.instagram.com/shubhankar5002",
  },
];

export const ARVR = [
  {
    id: 1,
    img: "/members/ANISH ROY.jpg",
    name: "Anish Roy",
    domain: "AR/VR",
    github: "https://github.com/RoyAnish074",
    linkedIn: "https://www.linkedin.com/in/anish-roy19",
    instagram: "https://instagram.com/royanish074?igshid=MzNlNGNkZWQ4Mg==",
  },
  {
    id: 2,
    img: "/members/pritam.png",
    name: "Pritam Kumar Pal",
    domain: "AR/VR",
    github: "https://github.com/PritamPaul01",
    linkedIn: "https://www.linkedin.com/in/pritam-pal-oo7",
    instagram: "",
  },
];

export const CloudTeam = [
  {
    id: 1,
    img: "/members/Archit Gupta.jpg",
    name: "Archit Gupta",
    domain: "Cloud and CyberSecurity",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 2,
    img: "/members/Subandhu.png",
    name: "Subandhu",
    domain: "Cloud and CyberSecurity",
    github: "https://github.com/retrojoker",
    linkedIn: "https://www.linkedin.com/in/subandhu/",
    instagram: "https://www.instagram.com/dontfollowmeyoullendupinmyarms/",
  },
  {
    id: 3,
    img: "/members/sourasish.png",
    name: "Sourasish Basu",
    domain: "Cloud and CyberSecurity",
    github: "https://github.com/SourasishBasu",
    linkedIn: "https://www.linkedin.com/in/sourasishbasu/",
    instagram: "https://www.instagram.com/_.sourasish/",
  },
  {
    id: 4,
    img: "/members/Tanisha.png",
    name: "Tanisha Verma",
    domain: "Cloud and CyberSecurity",
    github: "https://github.com/Tanishaa08",
    linkedIn: "https://www.linkedin.com/in/tanisha-verma-0118a623b/",
    instagram: "https://www.instagram.com/tanisha_08___/",
  },
  {
    id: 5,
    img: "/members/rahul.jpeg",
    name: "Rahul Biswas",
    domain: "Cloud and CyberSecurity",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 6,
    img: "/members/dhruv.png",
    name: "Dhruv Agarwal",
    domain: "Cloud and CyberSecurity",
    github: "",
    linkedIn: "",
    instagram: "",
  },
];

export const YT = [
  {
    id: 1,
    img: "/members/Paarth Pareek.jpeg",
    name: "Paarth Pareek",
    domain: "Youtube Hosting",
    github: "",
    linkedIn: "https://www.linkedin.com/in/paarth-pareek-5689a4218",
    instagram: "https://instagram.com/paarth233?igshid=OGQ5ZDc2ODk2ZA==",
  },
  {
    id: 2,
    img: "/members/Prakhar Singh.png",
    name: "Prakhar Singh",
    domain: "Youtube Hosting",
    github: "https://github.com/shrike0p",
    linkedIn: "https://www.linkedin.com/in/prakhar-singh-01",
    instagram: "https://www.instagram.com/_.prakhar._singh/",
  },
  {
    id: 3,
    img: "/members/APOORVA AANAND.jpg",
    name: "Apoorva Aanand",
    domain: "Youtube Hosting",
    github: "",
    linkedIn: "",
    instagram: "",
  },
  {
    id: 4,
    img: "/members/bhoomika.jpg",
    name: "Bhoomika",
    domain: "Youtube Hosting",
    github: "",
    linkedIn: "https://www.linkedin.com/in/bhoomika-sehta-a76886257",
    instagram: "https://instagram.com/bhooxmika?igshid=NGExMmI2YTkyZg==",
  },
];

export const GALLERY = [
  {
    id: 1,
    img: "/gallery/Devops/1.JPG",
    name: "Devops",
  },
  {
    id: 2,
    img: "/gallery/Eyespy/2.JPG",
    name: "Eye S.py Squid",
  },
  {
    id: 3,
    img: "/gallery/Devops/2.JPG",
    name: "Devops",
  },
  {
    id: 4,
    img: "/gallery/Frontend/4.png",
    name: "Frontend With Benefits",
  },
  {
    id: 5,
    img: "/gallery/Projectwing/1.png",
    name: "Project Wing",
  },
  {
    id: 6,
    img: "/gallery/Eyespy/3.JPG",
    name: "Eye S.py Squid",
  },
  {
    id: 7,
    img: "/gallery/Devops/3.JPG",
    name: "Devops",
  },
  {
    id: 8,
    img: "/gallery/Frontend/5.png",
    name: "Frontend With Benefits",
  },
  {
    id: 9,
    img: "/gallery/Eyespy/4.JPG",
    name: "Eye S.py Squid",
  },
  {
    id: 10,
    img: "/gallery/Projectwing/2.png",
    name: "Project Wing",
  },
  {
    id: 11,
    img: "/gallery/Frontend/6.png",
    name: "Frontend With Benefits",
  },
  {
    id: 12,
    img: "/gallery/Devops/4.JPG",
    name: "Devops",
  },
  {
    id: 13,
    img: "/gallery/Eyespy/5.JPG",
    name: "Eye S.py Squid",
  },
  {
    id: 14,
    img: "/gallery/Frontend/7.png",
    name: "Frontend With Benefits",
  },
];
